name: "Publish elixir packages to hex.pm"
description: "Publish elixir packages to hex.pm"
author: "CoderDennis"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "package"
  color: "purple"
